### ISSUE TITLE
知乎网站失效了，无法展开全文

### ISSUE THREAD

**Issue by Wolffy1994** [027xiguapi/code-box#11]
![1](https://github.com/user-attachments/assets/3adf7d47-4fc8-47d5-af19-eca6e2364ea0)
测试了许多遍都无法展开

**Comment by Wolffy1994** [comment]
测试网址：https://zhuanlan.zhihu.com/p/98404208

**Comment by 027xiguapi** [comment]
![image](https://github.com/user-attachments/assets/5b84bfc1-736f-4c61-8f87-95b6da5a7269)

谢谢，可以升级到0.3.1，解决问题
