### ISSUE TITLE
CSDN图片无法点击放大

### ISSUE THREAD

**Issue by ido2021** [027xiguapi/code-box#15]
开启插件之后访问CSDN博客，文章中的图片无法点击放大查看。
关闭插件并刷新页面则可正常操作.
复现地址：https://blog.csdn.net/Lanna_w/article/details/128322329

**Comment by 027xiguapi** [comment]
![image](https://github.com/user-attachments/assets/fd2c632d-d0cd-49e8-9fd7-80c1f3748e75)
我尝试了，可以放大图片
