### ISSUE TITLE
【自定义设置/页面插入css代码】希望增加对不同页面插入不同css代码功能

### ISSUE THREAD

**Issue by Jinvic** [027xiguapi/code-box#22]
如题，希望增加对不同页面插入不同css代码的功能，或者插入css代码只对特定页面有效。
有时设定好css样式后，切到别的网站仍然适用，需要手动关闭功能再刷新页面，比较麻烦。

**Comment by 027xiguapi** [comment]
可以，目前只对 CSDN/知乎/脚本之家/博客园/博客园/51CTO博客/php中文网/掘金/微信等网站有特殊处理，如果要加也是对这些网站设置，其他网站可能暂不支持
