### ISSUE TITLE
大佬，可以增加到搜狗浏览器吗

### ISSUE THREAD

**Issue by hncaiyin** [027xiguapi/code-box#23]
直接下载你的zip文件，用搜狗加载目录，可以看见插件配置页面，但是点击无效，没反应，实际登录知乎也没有效果，可以增加搜狗浏览器支持吗?谢谢

**Comment by 027xiguapi** [comment]
360浏览器也无法使用
![image](https://github.com/user-attachments/assets/1ff29fb5-debf-4018-a208-d4a544baa2c0)
![image](https://github.com/user-attachments/assets/a4af31b6-a44a-45b4-841c-eb659aa69d86)

**Comment by 027xiguapi** [comment]
建议换其他浏览器：比如 [Chrome](https://chrome.google.com/webstore/category/extensions?hl=zh-CN)、[Edge](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home?hl=zh-CN)、[Firefox](https://addons.mozilla.org/zh-CN/firefox/)

[搜狗浏览器 12 为什么插件无法安装？](https://feedback.browser.qq.com/faq?faqid=ae139ac1-36d4-12c4-4ceb-0437dab1e679&app=sogoubrowser)
