### ISSUE TITLE
不懂就问，刚用这个，这个需要money吗

### ISSUE THREAD

**Issue by dmarkdmark** [027xiguapi/code-box#24]
![Clip_2024-10-21_20-15-34](https://github.com/user-attachments/assets/94cedf8c-7701-4153-abaf-ddb470d7531f)

还是我哪里使用的不对

**Comment by 027xiguapi** [comment]
暂时不需要，我看见你的版本是 0.5.10，现在有更新版本你可以去插件商店下载，或去 下面链接下载
```
https://www.crxsoso.com/webstore/detail/acnnhjllgegbndgknlliobjlekgilbdf 
```

**Comment by dmarkdmark** [comment]
sry，忘记给扩展更新了，刚直接更新，0.8.4版本了
赞
