### ISSUE TITLE
360应用市场搜不到呢

### ISSUE THREAD

**Issue by nickolboy** [027xiguapi/code-box#26]
![image](https://github.com/user-attachments/assets/b31068d5-18c1-49c2-afd2-23acdda948e6)

**Comment by 027xiguapi** [comment]
![image](https://github.com/user-attachments/assets/a436783a-23c1-4213-9c96-537c144b1ae1)
![image](https://github.com/user-attachments/assets/81a5b32f-c9ea-46fc-b305-dab80ab6a671)


详细地址：https://ext.se.360.cn/#/extension-detail?id=acnnhjllgegbndgknlliobjlekgilbdf

**Comment by nickolboy** [comment]
奇了怪了，就是搜不到，点链接就是市场首页，难道歧视linux？

**Comment by 027xiguapi** [comment]
试一试这个：

https://www.crxsoso.com/webstore/detail/acnnhjllgegbndgknlliobjlekgilbdf
