### ISSUE TITLE
为什么要 管理下载内容的权限 ?

### ISSUE THREAD

**Issue by GmavionR** [027xiguapi/code-box#33]
![image](https://github.com/user-attachments/assets/5a181fc2-f878-4645-9356-da2821d2cece)
![image](https://github.com/user-attachments/assets/40b37441-60c3-4ebd-9bcc-3d65a027e756)

**Comment by 027xiguapi** [comment]
![image](https://github.com/user-attachments/assets/1a2097c8-5740-46a6-b5a2-08455b65d87b)
批量下载图片
