### ISSUE TITLE
【知乎】貌似免登录无法实现，一直还是跳转到登录页面

### ISSUE THREAD

**Issue by vagrant2046** [027xiguapi/code-box#9]
如题

**Comment by 027xiguapi** [comment]
非常感谢，可以提供一下复现链接吗？，最好配上截图说明

**Comment by Perfecto23** [comment]
@027xiguapi https://www.zhihu.com/question/294210442/answer/500385309
你看这个链接，自动展开但是内容不全，这应该是知乎接口没有返回全导致的吧？有什么方法可以绕过么。
然后就是点左上角首页直接去登录了，不能乱逛
![image](https://github.com/user-attachments/assets/a1398eca-2636-4071-a681-48de617b7f31)

**Comment by 027xiguapi** [comment]
> @027xiguapi https://www.zhihu.com/question/294210442/answer/500385309 你看这个链接，自动展开但是内容不全，这应该是知乎接口没有返回全导致的吧？有什么方法可以绕过么。 然后就是点左上角首页直接去登录了，不能乱逛 ![image](https://private-user-images.githubusercontent.com/91355573/355298673-a1398eca-2636-4071-a681-48de617b7f31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzAyNjAsIm5iZiI6MTcyMjkyOTk2MCwicGF0aCI6Ii85MTM1NTU3My8zNTUyOTg2NzMtYTEzOThlY2EtMjYzNi00MDcxLWE2ODEtNDhkZTYxN2I3ZjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA3MzkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYzRlNDhlNjY3NDUwZDQ0ZjljNzhlMGM0M2UwYmMzZTdlMjY3NGQxNWY1ZmZlODkyNjhjMzA5ZTk5OThjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z2f-fBVfNBMbKdIDZPn34FdL27-tOVk3xjzNstaET_k)

可以自定义关闭部分功能

![image](https://github.com/user-attachments/assets/68fe0d01-074c-4f92-92a3-7cca7672cf69)

**Comment by vagrant2046** [comment]
close
